### PR TITLE
Job board update 180423

### PR DESCRIPTION
**Pull request by ReynaldoBoulogne**
What it says on the tin :)

### CODE REVIEW

**Comment by Jim-Holmstroem** [comment]
blank out the positions of `af` instead of deleting the file, otherwise LGTM

**Comment by ReynaldoBoulogne** [comment]
Yes, thanks. I realized that after I had deleted the åf file :)

**Comment by Jim-Holmstroem** [comment]
* Re-add the `af.md`
* Rebase it on origin/master
* Squash all commits to one (possible in the same time as the rebase)

**Comment by Jim-Holmstroem** [comment]
fixed the rebase and added af.md back in https://github.com/Stockholm-AI/stockholm-ai/pull/95

**Comment by ReynaldoBoulogne** [comment]
Thank you Jim. I tried to do this earlier but failed. I'm going to brush up my Github skills for the next time.

**Pull request closed without merging**
