### PR TITLE
First try on a public calendar

### PR DESCRIPTION
**Pull request by Jim-Holmstroem**
Adds `stockholm.ai/calendar`

### CODE REVIEW

**Comment by Jim-Holmstroem** [comment]
Should add a link from the main page

**Comment by sjosund** [comment]
Now the calendar is both at the main page and at the separate calendar page. Also there’s a conflict message above the cal.

**Comment by Jim-Holmstroem** [comment]
what do you mean with conflict message?

**Comment by Jim-Holmstroem** [comment]
Perhaps the "contact us if you want stuff added" should be below?

**Comment by sjosund** [comment]
Oops, sorry my mistake. I think it looks great :)

**Pull request merged**
